### ISSUE TITLE
Network thread hanging

### ISSUE THREAD

**Issue by PhillHenry** [minorg/whoisclient#2]
I queried whois.dotarai.com but the code has been hanging for over 12 hours. I did a jstack and got the stacktrace below. It would be nice if there were a timeout facility.

I'm using version 1.0.1.

(On a side note, is there any easy way of separating the network code from the parsing code?)

```
"main" #1 prio=5 os_prio=0 tid=0x00007fef4c00d000 nid=0x22ea runnable [0x00007fef52597000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.net.SocketInputStream.read(SocketInputStream.java:127)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
	at org.apache.commons.io.IOUtils.toByteArray(IOUtils.java:462)
	at io.github.minorg.whoisclient.WhoisClient.__getRawWhoisRecord(WhoisClient.java:85)
	at io.github.minorg.whoisclient.WhoisClient.getWhoisRecord(WhoisClient.java:53)
	at io.github.minorg.whoisclient.WhoisClient.getWhoisRecord(WhoisClient.java:45)
```

**Comment by minorg** [comment]
The parser is in WhoisRecordParser.

**Comment by minorg** [comment]
The network code is bog standard blocking sockets.

I've deployed a 1.0.2-SNAPSHOT and released a 1.0.2 with a WhoisClient constructor overload that takes a SocketFactory. You can use this to set the socket timeout by e.g., subclassing DefaultSocketFactory, overloading createSocket(InetAddress, int), and setting socket.setSoTimeout before returning the socket.
